[workspace]
name = "torch-scatter"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-aarch64"]
preview = ["pixi-build"]

[package]
name = "torch-scatter"
version = "2.1.3dev0"

[system-requirements]
cuda = "12.9"

[package.build]
backend = { name = "pixi-build-python", version = ">=0.5.2" }

[package.build.config]
noarch = false
compilers = ["cxx", "cuda"]

[package.build-dependencies]
cmake = ">=3.29,<4"
ninja = ">=1.13,<2"
cuda-toolkit = "12.9.*"

[package.host-dependencies]
python = ">=3.12,<3.13"
pip = "*"
setuptools = "<82"

pytorch = "2.11.*"
torchvision = "0.26.*"
